[package]

name = "appendbuf"
version = "0.1.6"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
repository = "https://github.com/reem/rust-appendbuf.git"
description = "A Sync append-only buffer with Send views."
readme = "README.md"
license = "MIT"

[dependencies]
memalloc = "0.1"

